Repository materialsproject/maggma, pull requests merged in 2023-06, with the labels that each got.

#792 modify JSONStore file creation
  src/maggma/stores/mongolike.py
  tests/stores/test_mongolike.py
Labels: release:patch

#793 Disable worker timeouts by default
  src/maggma/cli/distributed.py
  src/maggma/cli/settings.py
Labels: release:patch

#795 Use tqdm.auto
  src/maggma/cli/multiprocessing.py
  src/maggma/cli/serial.py
  src/maggma/utils.py
Labels: release:patch

#737 python 3.11 support + expand python versions tested in CI
  .github/workflows/testing.yml
  requirements-optional.txt
  requirements.txt
Labels: dependencies, github_actions

#805 Explicitly close s3 client connections in `S3Store`
  src/maggma/stores/aws.py
Labels: release:patch

#794 Memray memory profiler support for mrun command line tool
  docs/getting_started/running_builders.md
  requirements-optional.txt
  setup.py
  src/maggma/cli/__init__.py
  src/maggma/cli/settings.py
  tests/cli/test_init.py
Labels: enhancement, release:minor

#808 Fixing bug in azure multi worker test
  tests/stores/test_azure.py
Labels: release:patch

#809 add patch method for submission resource
  src/maggma/api/resource/submission.py
  src/maggma/api/utils.py
  tests/api/test_submission_resource.py
Labels: release:patch

#811 fix the response field
  src/maggma/api/resource/submission.py
Labels: release:patch
