Repository materialsproject/maggma, pull requests merged in 2023-08, with the labels that each got.

#837 Allow maggma to be used without Azure
  src/maggma/stores/azure.py
Labels: release:patch

#829 allow >5GB and turn on multi-part uploads for AWS
  src/maggma/stores/aws.py
Labels: release:minor

#840 CI: small update to auto dependency workflow
  .github/workflows/upgrade-dependencies.yml
Labels: github_actions

#843 Aws store botocore fix
  src/maggma/stores/aws.py
  tests/stores/test_aws.py
Labels: release:patch

#847 JSONStore: enabled reading of MongoDB extended JSON files
  src/maggma/stores/mongolike.py
  tests/stores/test_mongolike.py
  tests/test_files/test_set/extended_json.json
Labels: release:minor
