Repository materialsproject/maggma, pull requests merged in 2023-11, with the labels that each got.

#879 Store.connect: fix force_reset kwarg implementations
  src/maggma/stores/compound_stores.py
  src/maggma/stores/file_store.py
  src/maggma/stores/gridfs.py
  src/maggma/stores/mongolike.py
  src/maggma/stores/shared_stores.py
Labels: enhancement, release:patch

#881 Ensure sort stage is after match in agg pipeline
  src/maggma/api/resource/utils.py
Labels: release:patch

#883 Update hint_scheme
  src/maggma/api/resource/read_resource.py
  src/maggma/api/utils.py
Labels: release:patch

#884 Fix aggregation pipeline kwargs
  src/maggma/api/resource/read_resource.py
Labels: release:patch

#887 Add missing `MontyStore` to list of stores
  docs/getting_started/stores.md
Labels: docs

#888 Remove hint in count for S3Store
  src/maggma/api/resource/read_resource.py
Labels: release:patch

#890 Remove key from sorting by default
  src/maggma/api/resource/utils.py
Labels: release:patch

#892 update package metadata in pyproject.toml
  pyproject.toml
  setup.py
Labels: github_actions, fix, pkg, housekeeping

#882 SSH tunnel support for S3Store
  docs/getting_started/using_ssh_tunnel.md
  docs/reference/stores.md
  mkdocs.yml
  src/maggma/stores/aws.py
  src/maggma/stores/gridfs.py
  src/maggma/stores/mongolike.py
  src/maggma/stores/ssh_tunnel.py
  tests/stores/test_aws.py
  tests/stores/test_ssh_tunnel.py
Labels: enhancement, release:minor, docs
