Repository materialsproject/maggma, pull requests merged in 2024-05, with the labels that each got.

#952 merge setup.py into pyproject.toml
  pyproject.toml
  setup.py
Labels: pkg, housekeeping

#954 Add support for python 3.12 to CI
  .github/workflows/testing.yml
  .github/workflows/upgrade-dependencies.yml
  requirements/macos-latest_py3.12.txt
  requirements/macos-latest_py3.12_extras.txt
  requirements/ubuntu-latest_py3.12.txt
  requirements/ubuntu-latest_py3.12_extras.txt
Labels: github_actions

#950 MongograntStore: make optional dependency, prepare for removal
  docs/getting_started/advanced_stores.md
  docs/getting_started/stores.md
  pyproject.toml
  src/maggma/stores/advanced_stores.py
Labels: enhancement, dependencies, release:minor, breaking

#958 Handle store error during finalize
  src/maggma/core/builder.py
Labels: release:patch, fix
