Repository materialsproject/maggma, pull requests merged in 2024-06, with the labels that each got.

#959 update decorators for moto v5
  pyproject.toml
  requirements/macos-latest_py3.10_extras.txt
  requirements/macos-latest_py3.11_extras.txt
  requirements/macos-latest_py3.12_extras.txt
  requirements/macos-latest_py3.9_extras.txt
  requirements/ubuntu-latest_py3.10_extras.txt
  requirements/ubuntu-latest_py3.11_extras.txt
  requirements/ubuntu-latest_py3.12_extras.txt
  requirements/ubuntu-latest_py3.9_extras.txt
  tests/stores/test_aws.py
  tests/stores/test_open_data.py
Labels: dependencies, release:patch, housekeeping

#964 Bugfix in sorting query operator
  src/maggma/api/query_operator/sorting.py
  tests/api/test_query_operators.py
Labels: release:patch

#968 mv mongogrant to optional dependency group
  pyproject.toml
Labels: release:patch

#971 pre-commit updates and Numpy 2.0 support
  .pre-commit-config.yaml
  docs/getting_started/simple_builder.md
  pyproject.toml
  src/maggma/__init__.py
  src/maggma/api/API.py
  src/maggma/api/__init__.py
  src/maggma/api/models.py
  src/maggma/api/query_operator/dynamic.py
  src/maggma/api/query_operator/pagination.py
  src/maggma/api/query_operator/sparse_fields.py
  src/maggma/api/query_operator/submission.py
  src/maggma/api/resource/aggregation.py
  src/maggma/api/resource/core.py
  src/maggma/api/resource/post_resource.py
  src/maggma/api/resource/read_resource.py
  src/maggma/api/resource/s3_url.py
  src/maggma/api/resource/submission.py
  src/maggma/api/resource/utils.py
  src/maggma/api/utils.py
  src/maggma/builders/group_builder.py
  src/maggma/builders/map_builder.py
  src/maggma/cli/multiprocessing.py
  src/maggma/cli/serial.py
  src/maggma/cli/source_loader.py
  src/maggma/cli/sources/__init__.py
  src/maggma/core/__init__.py
  src/maggma/stores/__init__.py
  src/maggma/stores/advanced_stores.py
  src/maggma/stores/aws.py
  src/maggma/stores/azure.py
  src/maggma/stores/compound_stores.py
  src/maggma/stores/gridfs.py
  src/maggma/stores/mongolike.py
  src/maggma/stores/open_data.py
  src/maggma/stores/ssh_tunnel.py
  src/maggma/utils.py
  src/maggma/validators.py
  tests/builders/test_copy_builder.py
  tests/builders/test_group_builder.py
  tests/builders/test_projection_builder.py
  tests/stores/test_advanced_stores.py
  tests/test_utils.py
  tests/test_validator.py
Labels: dependencies, release:patch, housekeeping

#969 Add content to README; documentation fixups
  README.md
  docs/concepts.md
Labels: docs

#974 Dependency tweaks
  docs/getting_started/running_builders.md
  docs/reference/stores.md
  pyproject.toml
Labels: dependencies
