Repository materialsproject/maggma, pull requests merged in 2024-01, with the labels that each got.

#904 special casing for thermo, xas and synth_descriptions collections in OpenData
  src/maggma/stores/open_data.py
  tests/stores/test_open_data.py
Labels: release:patch

#905 rm deprecated pkg_resources
  src/maggma/__init__.py
Labels: release:patch, pkg

#908 creating PandasMemoryStore for use by OpenDataStore
  setup.py
  src/maggma/stores/open_data.py
  tests/stores/test_open_data.py
Labels: release:minor

#910 Make get by key default false
  src/maggma/api/resource/read_resource.py
  tests/api/test_read_resource.py
Labels: release:patch
