Repository materialsproject/maggma, pull requests merged in 2024-08, with the labels that each got.

#985 capability to configure query on request
  src/maggma/api/resource/core.py
  src/maggma/api/resource/read_resource.py
  tests/api/test_read_resource.py
Labels: release:patch

#991 remove numpy<2 constraint
  pyproject.toml
Labels: dependencies, release:patch

#992 add python 3.12 to CI tests
  .github/workflows/testing.yml
Labels: github_actions, housekeeping

#994 require numpy>1.26
  pyproject.toml
Labels: dependencies
