Repository materialsproject/maggma, pull requests merged in 2024-02, with the labels that each got.

#911 updating for open data format change
  setup.py
  src/maggma/stores/open_data.py
  tests/stores/test_open_data.py
Labels: release:minor

#914 chunking for json normalization
  src/maggma/stores/open_data.py
Labels: release:patch

#919 open data refactor for integration with builders
  src/maggma/stores/open_data.py
  tests/stores/test_open_data.py
Labels: release:minor

#920 fix open data store connect and close and address future warnings for pandas
  src/maggma/stores/open_data.py
  tests/stores/test_open_data.py
Labels: release:patch

#923 Tweak docstrings to fix rendered docs
  .pre-commit-config.yaml
  src/maggma/api/API.py
  src/maggma/api/__init__.py
  src/maggma/api/models.py
  src/maggma/api/query_operator/core.py
  src/maggma/api/query_operator/dynamic.py
  src/maggma/api/query_operator/pagination.py
  src/maggma/api/query_operator/sorting.py
  src/maggma/api/query_operator/sparse_fields.py
  src/maggma/api/query_operator/submission.py
  src/maggma/api/resource/aggregation.py
  src/maggma/api/resource/core.py
  src/maggma/api/resource/post_resource.py
  src/maggma/api/resource/read_resource.py
  src/maggma/api/resource/s3_url.py
  src/maggma/api/resource/submission.py
  src/maggma/api/resource/utils.py
  src/maggma/api/utils.py
  src/maggma/builders/group_builder.py
  src/maggma/builders/map_builder.py
  src/maggma/builders/projection_builder.py
  src/maggma/cli/distributed.py
  src/maggma/cli/multiprocessing.py
  src/maggma/cli/rabbitmq.py
  src/maggma/cli/serial.py
  src/maggma/cli/source_loader.py
  src/maggma/cli/sources/__init__.py
  src/maggma/core/__init__.py
  src/maggma/core/builder.py
  src/maggma/core/store.py
  src/maggma/core/validator.py
  src/maggma/stores/__init__.py
  src/maggma/stores/advanced_stores.py
  src/maggma/stores/aws.py
  src/maggma/stores/azure.py
  src/maggma/stores/compound_stores.py
  src/maggma/stores/file_store.py
  src/maggma/stores/gridfs.py
  src/maggma/stores/mongolike.py
  src/maggma/stores/open_data.py
  src/maggma/stores/shared_stores.py
  src/maggma/stores/ssh_tunnel.py
  src/maggma/utils.py
  src/maggma/validators.py
  tests/api/test_api.py
  tests/api/test_read_resource.py
Labels: enhancement, release:patch, docs

#929 write all NaN and NaT Dataframe created values as null
  src/maggma/stores/open_data.py
Labels: release:patch
