Repository materialsproject/maggma, pull requests merged in 2024-12, with the labels that each got.

#1014 Minor fix to URI store
  src/maggma/stores/mongolike.py
Labels: release:patch, fix

#1020 [Feature] Allow Different Azure Authentication Methods
  src/maggma/stores/azure.py
  tests/stores/test_azure.py
Labels: enhancement, release:minor

#1021 Set explicit mode in zopen to address monty FutureWarning
  src/maggma/stores/mongolike.py
Labels: release:patch, pkg, housekeeping
